data61/anonlink-entity-service

- backend/entityservice/error_checking.py
- backend/entityservice/tasks/base_task.py
- backend/entityservice/tasks/comparing.py
- backend/entityservice/views/run/status.py
- docs/local-deployment.rst
Small fix to address #327. 
Adds error handling in the aggregation task.
> Handle missing results during aggregation

- backend/entityservice/tasks/solver.py
- backend/entityservice/utils.py
Old solver is deprecated, so let’s use the new one.
> Use new solver API in anonlink

- backend/requirements.txt
Note we were not using `yaml.load` anyway.
> Upgrade PyYAML to avoid CVE-2017-18342

- backend/entityservice/api_def/swagger.yaml
- backend/entityservice/init-db-schema.sql
- backend/entityservice/messages.py
- backend/entityservice/models/project.py
- backend/entityservice/tasks/permutation.py
- backend/entityservice/tasks/solver.py
- backend/entityservice/tests/conftest.py
- backend/entityservice/tests/test_results_correctness.py
- backend/entityservice/views/run/results.py
There are almost certainly relevant bits of documentation or testing that I missed and that need updating. Please let me know if you see them.
> Introduce groups result type

- Jenkinsfile.groovy
- docs/development.rst
- docs/tutorial/Dockerfile
- docs/tutorial/Permutations.ipynb
- docs/tutorial/Similarity Scores.ipynb
- docs/tutorial/tutorial-requirements.txt
Uses the `nbval` plugin for pytest, runs inside a docker container on Jenkins.
Like clkhash only tests that none of the notebook cells error.
Closes #110
> Have Jenkins test notebooks

- backend/entityservice/tests/conftest.py
- backend/entityservice/tests/test_project.py
- backend/entityservice/tests/test_project_uploads.py
- backend/entityservice/tests/util.py
Generalise upload tests to different output types and multiple parties.
> Test multiparty project uploads

- backend/Dockerfile
- deployment/entity-service/requirements.yaml
- deployment/entity-service/values.yaml
- frontend/Dockerfile
> Updates to the 1.11 deployment

- Jenkinsfile.groovy
- deployment/entity-service/templates/api-deployment.yaml
- deployment/entity-service/templates/highmemory-worker-deployment.yaml
- deployment/entity-service/templates/init-db-job.yaml
- deployment/entity-service/templates/monitor-deployment.yaml
- deployment/entity-service/templates/worker-deployment.yaml
- deployment/entity-service/values.yaml
- deployment/jobs/benchmark/timing-test-job.yaml
- deployment/jobs/clear-in-progress-job.yaml
- deployment/jobs/integration-test-job.yaml
- deployment/n1-coreos-secret.yaml
To be clear this was a "readonly" secret for a public docker image hosted on quay.io
> Remove quay.io pull secret

- README.md
- tools/build.sh
Also found the docker container build script was using the old repository
> Minor readme updates after azure dockerhub changes

- benchmarking/Dockerfile
- benchmarking/benchmark.py
- benchmarking/requirements.txt
- benchmarking/schema/default-linking-schema.json
Second PRs for multi party linkage benchmark.
Based on the group results from the PR #424 , it simply handle more than two parties which was quite hard coded in the benchmark.
> Benchmark multi party

- backend/entityservice/tests/test_deletes.py
- backend/entityservice/tests/test_project_uploads.py
Required changes for PR #427 : the deployment is slower, so we need to increase the timeout for some tests.
> Slow tests

- azure-pipelines.yml
- backend/entityservice/cache/active_runs.py
- backend/entityservice/cache/progress.py
- backend/entityservice/errors.py
- backend/entityservice/settings.py
- backend/entityservice/tasks/assert_valid_run.py
- backend/entityservice/tasks/base_task.py
- backend/entityservice/tasks/mark_run_complete.py
- backend/entityservice/tasks/project_cleanup.py
- backend/entityservice/tasks/run.py
- backend/entityservice/tests/test_project_run_results.py
- backend/entityservice/utils.py
- backend/entityservice/views/run/description.py
- deployment/entity-service/templates/configmap.yaml
- deployment/entity-service/values.yaml
- docs/development.rst
This builds upon  https://github.com/data61/anonlink-entity-service/pull/431 to track run state in the redis cache.
This should address #421
> Feature cache runs

- backend/entityservice/models/run.py
- backend/entityservice/settings.py
- deployment/entity-service/templates/configmap.yaml
Closes #443
See discussion in https://github.com/data61/anonlink-entity-service/pull/432/#discussion_r329404684
> Remove unused setting ENTITY_MATCH_THRESHOLD

- docs/concepts.rst
The only missing documentation about groups is in the `concepts.rst` file.
Some documentation is already available in the `swagger` file and a tutorial.
> Tiny bit of documentation for groups.

- docs/changelog.rst
Nested lists in rst require 3 spaces and a blank line before and after
> Fixup changelog rst for v1.12.0

- deployment/entity-service/Chart.yaml
- deployment/entity-service/requirements.yaml
- deployment/entity-service/values.yaml
Update our postgres dependency and bump the version of our chart.
> Update postgres dependency and bump chart version

- .azurePipeline/templateDockerBuildPush.yml
Also updates the base image. Recreation of #511
> CI: Skip building base image if not required

- docs/tutorial/cli.rst
the CLI docs still used `clkutil`.
> use anonlink client instead of clkhash

- deployment/entity-service/Chart.yaml
- deployment/entity-service/requirements.yaml
- deployment/entity-service/values.yaml
updating the helm chart.
We need a newer version of minio for the ES to work.
> update to latest stable minio and beta.3 es images

- docs/tutorial/Record Linkage API.ipynb
last notebook. Here, I added a section on external upload.
> added section about external upload

- base/Dockerfile
- base/requirements.txt
- benchmarking/requirements.txt
turns out the base image was broken.
This PR fixes this.
> update python3 version

- base/Dockerfile
Base wasn't building.
I think we are over pinning - is that a thing?
> Update openssl in base

- backend/entityservice/views/objectstore.py
> Connect to object store using TLS if configured to

- backend/alembic/env.py
- deployment/entity-service/templates/init-objectstore-job.yaml
- deployment/entity-service/values.yaml
Fix for https://github.com/data61/charts/pull/1#issuecomment-782947833
> Update env var name in object store init job

- deployment/entity-service/templates/_helpers.tpl
- deployment/entity-service/templates/api-deployment.yaml
- deployment/entity-service/templates/api-service.yaml
- deployment/entity-service/templates/configmap.yaml
- deployment/entity-service/templates/es-credentials.yaml
- deployment/entity-service/templates/highmemory-worker-deployment.yaml
- deployment/entity-service/templates/init-db-job.yaml
- deployment/entity-service/templates/init-objectstore-job.yaml
- deployment/entity-service/templates/initial-objectstore-config.yaml
- deployment/entity-service/templates/monitor-service.yaml
- deployment/entity-service/templates/monitoring-configmap.yaml
- deployment/entity-service/templates/worker-autoscale.yaml
- deployment/entity-service/templates/worker-deployment.yaml
- deployment/entity-service/values.yaml
Applies recommendations from 
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels and https://helm.sh/docs/chart_best_practices/labels/#standard-labels
> Update k8s labels

- .azurePipeline/templatePublishLogsFromPods.yml
- deployment/entity-service/templates/api-deployment.yaml
In a previous commit I changed the labels and hadn't noticed that I broke the Azure tasks that fetch individual container logs - this PR fixes that.
> Fix azure k8s logging selections

- backend/alembic/versions/e321799791b7_add_err_msg_to_runs.py
- backend/entityservice/database/insertions.py
- backend/entityservice/database/models/models.py
- backend/entityservice/database/selections.py
- backend/entityservice/integrationtests/dbtests/test_insertions.py
- backend/entityservice/tasks/base_task.py
- backend/entityservice/tasks/comparing.py
- backend/entityservice/tasks/pre_run_check.py
- backend/entityservice/tasks/solver.py
- backend/entityservice/views/run/status.py
We now return a reason why a run failed.
closes #617
> Feature return error message

- base/Dockerfile
alpine updated the python 3.8 package and deleted the old version. Thanks.
also openssl
> update python in base image

- backend/entityservice/tasks/encoding_uploading.py
> remove warning log

- base/Dockerfile
and update packages to work with it.
> update to current alpine 3.14.1

- backend/entityservice/object_store.py
- backend/entityservice/tasks/encoding_uploading.py
- backend/entityservice/views/project.py
- docs/changelog.rst
As the title says, once we have ingested the data, we clean up on the object store.
> delete upload object store files after db ingestion
