- backend/requirements.txt
1. Fix Tornado version. Tornado released v6 on 1st March, which removes some deprecated APIs that we use. This caused things to crash.
2. Update Redis to 3.2.0.
> Dependency hell

- deployment/entity-service/templates/configmap.yaml
- deployment/entity-service/templates/init-db-job.yaml
I needed to use an external postgres provider for my test cluster, which meant I had to modify some templates. This PR enables users to connect the entity service to a a postgres server of their choosing. Pretty basic - if/else condition to see if postgres is being provisioned, if it is then set the database server to `{{.Release.Name }}-{{ .Values.postgresql.nameOverride}}`. If provisioning is disabled, use `{{ .Values.postgresql.nameOverride }}` instead.
This is working on my home cluster, and it passed the integration tests.
> Add support for external postgres 

- backend/entityservice/__init__.py
- backend/entityservice/async_worker.py
- backend/entityservice/default_logging.yaml
- backend/entityservice/errors.py
- backend/entityservice/logger_setup.py
- backend/entityservice/logging.yaml
- backend/entityservice/settings.py
- backend/entityservice/verbose_logging.yaml
- backend/requirements.txt
Instead of having the logging config all hardcoded we can read from a yaml file.
Addresses issue #323.
Fixes a few issues with logging too (e.g. including the timestamp twice).
> Configurable logging

- backend/entityservice/database/insertions.py
- backend/entityservice/init-db-schema.sql
- backend/entityservice/serialization.py
- backend/entityservice/settings.py
- backend/entityservice/tasks/comparing.py
As part of this, we remove `chunk_size` from `runs` in the database as the chunk size no longer depends on the job size.
> Use Anonlink chunking API

- backend/entityservice/models/project.py
- backend/entityservice/tasks/comparing.py
Two bugfixes:
1. The merging of similarities is currently crashing because of errors that were not caught by the tests. This is bad. These two line changes fix it.
2. Read `number_parties` correctly when making a project.
> Fix chunk merging (and one other minor thing)

- backend/entityservice/tasks/comparing.py
- backend/entityservice/tasks/permutation.py
- backend/entityservice/tasks/run.py
- backend/entityservice/tasks/solver.py
This generalises the worker functions to many parties, to make it easier to enable multi-party linkage. Changes to tests are not necessary as everything is equivalent for 2-party linkage.
>  Generalise worker to many parties

- Jenkinsfile.groovy
- benchmarking/Dockerfile
- Fails if the benchmark container exits incorrectly (due to bad configuration).
- Fails if the benchmark results contain status=ERROR entries.
- Removes the default server address for benchmark container.
Closes #361
> Have jenkins fail if the benchmark errors

- backend/entityservice/api_def/swagger.yaml
- backend/entityservice/models/project.py
- backend/entityservice/tests/conftest.py
- backend/entityservice/tests/test_project.py
- backend/entityservice/views/project.py
The only result type that works with multi-party linkage is `”groups”`. This PR makes a project POST request fail if `number_parties` > 2 but `result_type` ≠ groups.
> Fail on invalid result_type/number_parties combination

- backend/Dockerfile
There are a couple of [minor CVE that quay.io has picked up](https://quay.io/repository/n1analytics/entity-app/manifest/sha256:0bd94c0f5917a634010c8a1cd159c8a5eeb7531d21015f4cca6a5bdfd73a937d?tab=vulnerabilities&fixable=true) in our packaged version of python3. 
I suspect updated alpine to 3.8 or 3.9 will be enough to fix them.
> Update alpine base image to 3.8

- backend/entityservice/__init__.py
- backend/entityservice/database/util.py
- backend/entityservice/error_checking.py
- backend/entityservice/logger_setup.py
- backend/entityservice/settings.py
- backend/entityservice/tests/test_project.py
- backend/entityservice/verbose_logging.yaml
- backend/entityservice/views/project.py
- backend/entityservice/views/run/list.py
- docs/logging.rst
- tools/docker-compose.yml
I was [reading up on the flask Application Context](
http://flask.pocoo.org/docs/1.0/appcontext/#storing-data) and saw that the recommended approach for keeping a single database connection is slightly different to what we have.
I also added a debug log message to this teardown, and tweaked the *verbose logging* config so a developer can easily see the debug message. Note this changes the default docker-compose deployment to make including verbose logging a simple uncomment operation.
See also https://github.com/data61/anonlink-entity-service/issues/385
> Tweak database connection tear down and logging

- .azurePipeline/k8s_test_job.yaml.tmpl
- .azurePipeline/templateDockerBuildPush.yml
- azure-pipelines.yml
- docs/devops.rst
- docs/index.rst
That was quite painful, but it is finally working end to end!!!
The integration step using docker compose has been removed to run these tests only using kubernetes.
We were otherwise running twice the same tests on different deployment.
With this pipeline, we are still testing the docker compose and the kubernetes deployment, but running different tests on each.
On the docker compose deployment, we run the benchmark and the tutorial tests.
On k8s, we run the integration tests. 
It was preferred as the integration tests are BIG, and takes a long time, so it is better t use some beefy infrastructure instead of a single small VM running the whole service (which was tricky because of timeouts).
Note: this is **not** deploying a release, which is out of scope for this work.
Note 2: this is to …
> Feature pipeline integration tests

- backend/Dockerfile
- backend/requirements.txt
A package I've not heard of, that we don't directly use has a xml parsing vulnerability.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-20843
This PR updates our base alpine image to remove the vulnerability and updates celery to a compatible version.
> Update alpine to 3.10

- benchmarking/benchmark.py
- benchmarking/requirements.txt
- benchmarking/schema/experiments.json
- deployment/jobs/benchmark/timing-test-job.yaml
Two main features added at the same time (they could have been split).
Use of boto3 for the benchmark to be able to push the results to s3 instead of relying on k8s volumes which are hard to access afterward.
A parameter `repetition` has been added to an experiment schema to be able to repeat the same experiment a number of time in the same benchmarking k8s job. This should reduce the number of issue we could observe when running 100 times 1M*1M linkage as we were previously repeating the same k8s jobs 100 times, which can have issues with volumes which cannot be shared.
> Benchmark repeat parameter and results pushed to s3

- backend/entityservice/__init__.py
- backend/entityservice/async_worker.py
- backend/entityservice/cache.py
- backend/entityservice/database/util.py
- backend/entityservice/models/run.py
- backend/entityservice/settings.py
- backend/entityservice/tasks/project_cleanup.py
- backend/entityservice/tasks/stats.py
- backend/entityservice/utils.py
- backend/entityservice/views/auth_checks.py
- backend/entityservice/views/general.py
- backend/entityservice/views/project.py
- backend/entityservice/views/run/description.py
- backend/entityservice/views/run/list.py
- backend/entityservice/views/run/results.py
- backend/entityservice/views/run/status.py
Simplify the access to dabases to a single way:
```
with DBConn() as conn:
...
```
It will under the hood handle how to get a connection: either using a connection pool if available, or creating a single use connection.
The two main entry points which behave differently are due to the application having different entry points: mainly one for celery and one for flask.
Each behaves quite differently (yeah...)
But with these changes a dev will not have to worry from where the method is called.
The PR may also look bigger than what it is: I removed some method to create databases connections, to use the single way, which was repeated on a number of files.
> Feature connection pools

- backend/entityservice/database/util.py
- backend/entityservice/views/run/results.py
To print an exception in a log, the line 
```
logger.warning("Can't connect to database", e)
```
fails raising: "TypeError: not all arguments converted during string formatting"
Instead, as we are mainly printing the exception in a `try except` context, use the param `exc_info=True` to print it.
> Fix exception log

- benchmarking/benchmark.py
First of two PRs related to multi party linkage.
First one: using groups instead of mappings, and introducing a new metric for the grouping output.
In this PR, it is still hard coded to be ran for two parties only.
> Use groups instead of mapping in the benchmark.

- azure-pipelines.yml
First purge, then delete what is remaining. The only code modification is permuting the two steps.
The pipeline is sometimes failing during the `purge deployment` step because:
`Error: configmaps "es199430f5.v1" not found`.
> Permute cleaning steps in azure pipeline.

- .azurePipeline/k8s_test_job.yaml.tmpl
Otherwise, thed efault value is 6, which means that the job restarts up to 6 time a pod if the previous one failed.
> backoffLimit for the test job set to 0.

- benchmarking/linkage-bench-cache-experiments.json
Threshold 0.8 is chosen for the 3 party case because the results were quite good.
> Benchmark test on CI runs 3 parties linkage 

- backend/entityservice/cache/connection.py
- backend/entityservice/settings.py
- deployment/entity-service/templates/configmap.yaml
- deployment/entity-service/values.yaml
As Wilko pointed out in https://github.com/data61/anonlink-entity-service/pull/430#discussion_r327941353 all the other redis settings are fully configurable except for the sentinel name. This fixes this poor state of affairs.
> Make sentinel name configurable

- backend/entityservice/cache/helpers.py
- backend/entityservice/cache/progress.py
This PR builds upon the refactoring in https://github.com/data61/anonlink-entity-service/pull/430 by changing the internal redis data structure used to store the progress from a string to a hash.
This will enable us to store other data such as state in the same redis hash object.
> Refactor cache progress to use redis hash

- .azurePipeline/getPodsLogs.py
- .azurePipeline/templatePublishLogsFromPods.yml
- azure-pipelines.yml
- backend/entityservice/tests/test_admin.py
- docs/devops.rst
Add an extra step in our azure pipeline to publish the logs of the entity-service pods when tests are failing.
First, use a python script to download the logs (easier with python than bash, and I already had the script locally), then, create an azure template for steps running the python script and publishing the logs in azure artifacts, finally integrate this template in the main pipeline.
Note: I included a commit which will need to be reversed: I introduce a test made to fail (directly raising an exception).
> Feature k8s pods log extraction

- deployment/entity-service/Chart.yaml
- deployment/entity-service/templates/api-deployment.yaml
- deployment/entity-service/templates/configmap.yaml
- deployment/entity-service/templates/highmemory-worker-deployment.yaml
- deployment/entity-service/templates/logging-configmap.yaml
- deployment/entity-service/templates/worker-deployment.yaml
- deployment/entity-service/values.yaml
- docs/changelog.rst
- docs/production-deployment.rst
This PR is about adding possibility to configure the entity-service logging in deployment.
To do this, a user has to:
- create a logging configuration file which the entity-service can use (out of scope for this PR)
- create and publish on k8s a configmap from this logging configuration file (documented)
- add the corresponding parameters in the deployment configuration (documented in docs and in `values.yaml`)
Under the hood and following the documentation, a configmap is created from the logging file with a selected key. Without a key, each key from the configmap would create its own file when loaded in a volume.
Then, when selecting a logging configmap at deployment time, the env var configmap will update the env var `LOG_CFG` pointing to a file which will be created from the logging …
> Feature k8s logging

- backend/entityservice/api_def/swagger.yaml
- backend/entityservice/init-db-schema.sql
- backend/entityservice/messages.py
- backend/entityservice/models/project.py
- backend/entityservice/tasks/permutation.py
- backend/entityservice/tasks/run.py
- backend/entityservice/tasks/solver.py
- backend/entityservice/tests/conftest.py
- backend/entityservice/tests/test_project_run_listing.py
- backend/entityservice/tests/test_project_run_results.py
- backend/entityservice/tests/test_project_run_status.py
- backend/entityservice/tests/test_project_uploads.py
- backend/entityservice/tests/test_results_correctness.py
- backend/entityservice/tests/util.py
- backend/entityservice/views/auth_checks.py
- backend/entityservice/views/project.py
- backend/entityservice/views/run/results.py
- docs/changelog.rst
- docs/concepts.rst
- docs/development.rst
- docs/future.rst
- docs/security.rst
- docs/tutorial/Record Linkage API.ipynb
The goal of this PR is to remove the `mapping` output type from the entity-service. The `mapping` output type is indeed redundant with the `groups` output type for 2 parties, however, the output representation is slightly different.
Few notes:
- the documentation is horrible to update as there are a lot of things out of date.
- the tutorial python notebooks are not manageable from here: we are mainly testing clkhash
- most of the docs requires to have the entity-service already available (they point to `testing.es.data61.xyz`) which makes them impossible to keep up to date in the same PR as the one modifying the service
> Feature delete mapping

- backend/entityservice/database/insertions.py
- backend/entityservice/views/run/list.py
- backend/requirements.txt
- docs/changelog.rst
It all started with this strange failure in a clkhash test:
```
State: queued
Stage (1/3): waiting for CLKs
Progress: 100.00%
State: queued
Stage (1/3): waiting for CLKs
Progress: 100.00%
State: queued
Stage (2/3): compute similarity scores
State: running
Stage (3/3): compute output
State: running
Stage (4/3): there is no description for this stage
```
It turns out, that the entity service is naughty.
The problem is around the detection of the race condition to start a run twice.
The idea is that a run's state is set to `created` after creation, and only once all data provider have uploaded the necessary clks, the run state gets promoted to `queued` and, consequently, the run execution gets started.
However, some naughty code in `views/run/list.py:post` did some premature clk checking and …
> Fix starting runs

- backend/entityservice/tests/test_project_run_description.py
- backend/entityservice/tests/test_project_run_status.py
- backend/entityservice/tests/util.py
This PR will close #457 
Currently, the entity-service is trying to do unit tests in an end to end way. For example, the removed tests were about testing the run endpoint by creating full runs.
These full runs are already created in a number of other tests (e.g. the ones where we check the validity of the output of a run).
So in this PR, I removed some tests about intermediary results such as checking that a run is progressing normally and testing the run endpoint.
However, this is slightly against the tests visions where each test describe what it is "unit" testing. In the approach I started, we run the whole end to end pipeline and on the way test each part. 
But from 327 tests running in 7m 40s on my machine with a simple local deployment on the service, the PR reduced the number of …
> Remove redundant tests

- backend/Dockerfile
Wheel has become required to install anonlink. Not sure why...
At the same time, update docker alpine base image.
closes #468
This issue is currently blocking any other builds as they cannot build the anonlink-app image.
> Install wheel and update base docker image.

- backend/entityservice/api_def/swagger.yaml
- backend/entityservice/database/insertions.py
- backend/entityservice/init-db-schema.sql
- backend/entityservice/models/project.py
- backend/entityservice/tests/test_project.py
- backend/entityservice/views/serialization.py
This historic PR marks the beginning of blocking support in the entity service.
I added the flag 'uses_blocking' to the project. This can be set at creation, and will be reported in the ProjectDescription. Internally, this is stored as a flag in the project table in the database.
The idea is that all following actions will consult the DB to decide how to handle data upload, candidate creation and solving...
> Feature create blocking project

- deployment/entity-service/values.yaml
- deployment/jobs/benchmark/timing-test-job.yaml
- deployment/jobs/integration-test-job.yaml
- docs/devops.rst
- docs/production-deployment.rst
This started as just updating a dead hyperlink but has ended up being misc updates to the Kubernetes deployment docs.
Closes #471
> Updates production deployment documentation.

- azure-pipelines.yml
- deployment/entity-service/requirements.yaml
- deployment/entity-service/templates/configmap.yaml
- deployment/entity-service/values.yaml
- docs/tutorial/cli.rst
We recently noticed an issue with redis-ha not being "highly available" on our small test kubernetes cluster during cluster scaling events.
Before digging into it too much this PR brings our minio and redis chart dependencies up to date.
> Update redis and minio chart versions

- .azurePipeline/templatePublishLogsFromPods.yml
- azure-pipelines.yml
- backend/entityservice/__init__.py
- backend/entityservice/async_worker.py
- backend/entityservice/database/insertions.py
- backend/entityservice/logger_setup.py
- backend/entityservice/settings.py
- backend/entityservice/tests/test_serialization.py
- backend/entityservice/tests/test_utils.py
- backend/entityservice/tests/util.py
- backend/entityservice/tracing.py
- backend/entityservice/utils.py
- deployment/entity-service/templates/api-deployment.yaml
- deployment/entity-service/templates/configmap.yaml
- deployment/entity-service/templates/highmemory-worker-deployment.yaml
- deployment/entity-service/templates/init-db-job.yaml
- deployment/entity-service/templates/monitoring-configmap.yaml
- deployment/entity-service/templates/worker-deployment.yaml
- deployment/entity-service/values.yaml
- docs/logging.rst
Brings Jaeger/opentracing support back to life.
Refactors some of the logging config to be reused in the tracing config. I just pulled out the yaml config file loader and added tests.
Restructures the config via k8s to be a bit simpler - now all monitoring related config files are mounted in `/var/config`, the filenames are still passed in via ENV vars.
The default `values.yaml` file for our helm chart now includes annotations that will enable opentracing via a jaeger sidecar - if the cluster supports it. It has no effect on clusters that don't have jaeger enabled so I don't think it is a big deal to enable by default.
I uncommented the logging config in the values.yaml file so it is actually tested/used. It needs improvement.
> Revive jaeger

- backend/entityservice/database/insertions.py
- backend/entityservice/tasks/comparing.py
- backend/entityservice/tasks/pre_run_check.py
Figured I'd pay back some technical debt before embarking on my next feature.
Closes #442
> Detect invalid encoding size earlier

- backend/entityservice/database/selections.py
- backend/entityservice/tasks/encoding_uploading.py
- backend/entityservice/views/auth_checks.py
- backend/entityservice/views/project.py
- base/requirements.txt
Replaces #503. I can't review because I opened this PR.
> Feature blocking

- .azurePipeline/templateDockerBuildPush.yml
- azure-pipelines.yml
The condition in azure didn't seem to take effect so we now check whether to skip the expensive image building in bash. I've tried various combinations of using strings and booleans in the main azure script and docker build template and cannot make Azure Pipelines do what I expect.
I updated the base digest too
> Skip build in bash if azure isn't playing along

- .azurePipeline/templateDockerBuildPush.yml
- azure-pipelines.yml
- docs/development.rst
- docs/devops.rst
> CI system now automatically uses latest base image

- .azurePipeline/runDockerComposeTests.sh
- azure-pipelines.yml
- backend/entityservice/cache/progress.py
- backend/entityservice/integrationtests/dbtests/test_insertions.py
- backend/entityservice/integrationtests/redistests/test_progress.py
- backend/entityservice/integrationtests/redistests/test_status.py
- backend/entityservice/models/project.py
- docs/development.rst
- docs/devops.rst
- tools/ci.yml
We currently have *end to end* tests that use just the REST api, and a few (not many) *unit tests* that test isolated Python functions. 
This PR starts to add *integration tests* which have direct access to the support services - e.g. direct access to redis or postgres to check and/or manipulate the state. This is useful as it allows us to have smaller units of testable code relying on support services.
> Integration tests

- tools/ci.yml
- tools/docker-compose.yml
This modification to the docker-compose files allows the app to push to jaeger during local deployment
via docker.
> Fix local jaeger

- .azurePipeline/templatePublishLogsFromPods.yml
- azure-pipelines.yml
- deployment/entity-service/requirements.yaml
- deployment/entity-service/templates/NOTES.txt
- deployment/entity-service/values.yaml
A new version of helm has been released. We were not pinning the version and many Azure devops commands/tasks required the old version.
Updates the note printed out in helm after a deploy.
> Update azure and kubernetes deployment notes 

- benchmarking/benchmark.py
- benchmarking/default-experiments-wawo-blocking.json
- benchmarking/requirements.txt
- docs/benchmarking.rst
This extends the benchmark script to be able to run experiments which use blocking.
An experiment definition for blocking looks like this:
```
{
"sizes": ["100K", "100K"],
"use_blocking": true,
"threshold": 0.80
}
```
The corresponding 'clknblocks' files are uploaded to S3.
For now I haven't changed the `default-experiements.json` file, as the blocked experiments take a very long time and will most likely trigger a timeout. 
Once we addressed that issue in the entity service, we can replace `default-experiements.json` with `default-experiements-wawo-blocking.json`.
> Feature blocky benchmark

- backend/entityservice/cache/helpers.py
- backend/entityservice/cache/progress.py
- backend/entityservice/database/selections.py
- backend/entityservice/init-db-schema.sql
- backend/entityservice/tasks/comparing.py
- backend/entityservice/tasks/run.py
- backend/entityservice/views/run/status.py
This calculation now takes into account the use of blocking. Also because it seemed somewhat non-trivial to compute I added caching in redis.
Closes #542
> Fix calculation of total number of comparisons

- .azurePipeline/runDockerComposeTests.sh
- azure-pipelines.yml
- tools/docker-compose.yml
Just a small tidy up, there was some inconsistency between how we used docker-compose and how the average user might expect to.
> Use docker-compose without having to set the --project-directory

- README.md
- backend/.dockerignore
- backend/entityservice/api_def/openapi.yaml
- backend/entityservice/database/insertions.py
- backend/entityservice/encoding_storage.py
- backend/entityservice/init-db-schema.sql
- backend/entityservice/object_store.py
- backend/entityservice/serialization.py
- backend/entityservice/tasks/__init__.py
- backend/entityservice/tasks/encoding_uploading.py
- backend/entityservice/tasks/project_cleanup.py
- backend/entityservice/tasks/stats.py
- backend/entityservice/tests/test_utils.py
- backend/entityservice/utils.py
- backend/entityservice/views/auth_checks.py
- backend/entityservice/views/general.py
- backend/entityservice/views/objectstore.py
- backend/entityservice/views/project.py
- backend/entityservice/views/util.py
- deployment/entity-service/Chart.yaml
- deployment/entity-service/requirements.yaml
- deployment/entity-service/templates/highmemory-worker-deployment.yaml
- deployment/entity-service/templates/worker-deployment.yaml
- e2etests/config.py
- e2etests/tests/conftest.py
- e2etests/tests/test_project_uploads.py
- e2etests/tests/test_uploads.py
- e2etests/util.py
- tools/docker-compose.yml
Adds backend implementation of pulling blocking information from external object store.
As we haven't defined a binary format for blocking information I made the decision to stick with the JSON format, but simply process it from an external file.
> Feature external blocks

- azure-pipelines.yml
- benchmarking/Dockerfile
- e2etests/tests/test_project_run_results.py
- e2etests/tests/test_project_uploads.py
- e2etests/tests/test_results_correctness.py
- e2etests/tests/test_results_correctness_multiparty.py
I found these error messages in the Azure logs when building the benchmark container:
```
Step 10/14 : RUN adduser user &&     chown user:user /app /var/log /cache
---> Running in e69fcbfba95d
Adding user `user' ...
Adding new group `user' (1000) ...
Adding new user `user' (1000) with group `user' ...
Creating home directory `/home/user' ...
Copying files from `/etc/skel' ...
New password: Password change aborted.
passwd: Authentication token manipulation error
passwd: password unchanged
Use of uninitialized value $answer in chop at /usr/sbin/adduser line 556.
Use of uninitialized value $answer in pattern match (m//) at /usr/sbin/adduser line 557.
Try again? [y/N] Changing the user information for user
Enter the new value, or press ENTER for the default
Full Name []: 	Room Number []: …
```
> disable password prompt for adduser

- backend/entityservice/tasks/project_cleanup.py
we had this problem in the CI that sometimes the tests would fail with a `NoSuchBucket` exception.
It turns out that this happens during project cleanup. I wrapped the offending line in a try-catch and log a warning message.
> catching NoSuchBucket exception at cleanup

- backend/entityservice/views/objectstore.py
- e2etests/tests/test_project_uploads.py
This test failed intermittently on Azure with 
`minio.error.NoSuchBucket: NoSuchBucket: message: The specified bucket does not exist.`
I cannot reproduce this with a local deployment. Also, I can run the test locally against the deployed service without errors. 
I still don't know why this happens. I propose a fix, that, at upload authorization, checks if the bucket exists and if not creates it.
You can see it working in the [CI logs](https://dev.azure.com/data61/Anonlink/_build/results?buildId=2272&view=logs&j=aac7439e-97d6-512d-3e06-b7446a540cac&t=d5e89444-f1ca-5d4b-026a-e4bc7ee5428c) line 5288.
> fix NoSuchBucket error

- backend/entityservice/tasks/encoding_uploading.py
Field names in HTTP headers are case-insensitive, some networks decide that means that can normalize the headers however they like, presumably to keep things interesting.
On one such network the backend errors with the following:
```
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
R = retval = fun(*args, **kwargs)
File "/var/www/entityservice/tasks/base_task.py", line 87, in __call__
return super(TracedTask, self).__call__(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__
return self.run(*args, **kwargs)
File "/var/www/entityservice/tasks/encoding_uploading.py", line 72, in pull_external_data
count = int(stat.metadata['X-Amz-Meta-Hash-Count'])
KeyError: …
```
> Fix case sensitivity in minio metadata

- backend/entityservice/tasks/comparing.py
This object store deletion was only triggered in benchmarks and not in tests.
> Bug fix - Minio python API now requires a "DeleteObject"

- deployment/entity-service/Chart.yaml
- deployment/entity-service/templates/init-db-job.yaml
- deployment/entity-service/templates/init-objectstore-job.yaml
Both the database migration and object store init job's handle being run multiple times. This small tweak to the helm hooks ensures those jobs also get run after an upgrade - enabling a kubernetes deployment installed via helm to upgrade even if new minio buckets, policies or users are added, or more commonly if the database schema changes.
Object store init job on running twice:
```
mc version RELEASE.2021-02-14T04-28-06Z
== Initialising Object Store ==
mc: <ERROR> Unable to make bucket `minio/uploads`. Your previous request to create the named bucket succeeded and you already own it.
Added user `EXAMPLE_UPLOAD_ACCESS_KEY` successfully.
Policy writeonly is set on user `EXAMPLE_UPLOAD_ACCESS_KEY`
== Object Store Root Upload User Created ==
Added user `EXAMPLE_DOWNLOAD_ACCESS_KEY` …
```
> Run migration jobs after upgrade as well as after install

- azure-pipelines.yml
Add a step in the integration test pipeline validating if a test result file exists, otherwise fails.
This feature is only added for the integration tests, not being sure if this is required for other steps.
Few notes:
- a [feature request](https://github.com/microsoft/azure-pipelines-tasks/issues/13275) has been opened in Azure Pipeline `PublishTestResult` task for it to fail if no test file are present (instead of just printing a warning
- the k8s task which does the `cp` is not failing if the file is not present. I did not find any way to parametrise this from their [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops#commands) and it seems to be a common issue with other commands such as …
> CI e2e test, validate test file existence

- backend/entityservice/database/insertions.py
- backend/entityservice/database/selections.py
- backend/entityservice/encoding_storage.py
- backend/entityservice/error_checking.py
- backend/entityservice/tasks/comparing.py
- backend/entityservice/tasks/encoding_uploading.py
- backend/entityservice/tests/test_encoding_storage.py
- backend/entityservice/views/project.py
- e2etests/tests/test_results_correctness.py
- e2etests/util.py
Related to issue #632.
Block names were limited to 64 chars, for P-Sig we may very well want to use block ids that are based on bloom filters... a 64 char limit would impose a max bloom filter size of 512 bits (assuming a perfect encoding unlike json).
This small change increases the column size to 512 chars, although happy to increase further or remove the character limitation.
> Hash provided block identifier before storing in DB

- backend/entityservice/views/run/status.py
- backend/entityservice/views/serialization.py
Once a run is complete, the status now reports the total number of comparisons.
> add total number of comparisons to completed status

- backend/entityservice/tasks/comparing.py
I noticed that the similarity score results can contain duplicates. 
The reason is that if a candidate pair appears in more than one block, they will produce more than one similarity score.
This PR introduces a simple unique value iterator to remove the duplicates from the similarity scores stream. The stream is already sorted, so duplicates will appear one after the other.
> de-duplicate similarity scores

- .github/dependabot.yml
Dependabot is now natively built into github, the old method is no longer working ([recent PR comment](https://github.com/data61/anonlink-entity-service/pull/657#issuecomment-902263047))
You can read more at:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/upgrading-from-dependabotcom-to-github-native-dependabot#upgrading-to-github-native-dependabot
This PR creates the new configuration for dependabot stored in the repo.
> Upgrade to native dependabot

- base/Dockerfile
- base/requirements.txt
includes bulk update of python dependencies. 
`connexion` is difficult. It wants Flask < 2.
> Update base again
